language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

notifications:
    webhooks: http://homu.doublebitstudios.com:54856/travis

branches:
    only:
        - auto
        - master
